# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InterviewMeApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod'Firebase/Auth'
pod'Firebase/Database'
pod'TwilioVideo', '~> 2.0'
pod'SwiftyCam', :git => 'https://github.com/Awalz/SwiftyCam.git', :branch => 'Swift4'
pod'RecordButton'
  # Pods for InterviewMeApp

end
